language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: stable
    - rust: beta
  fast_finish: true

script:
  - rustup target add thumbv6m-none-eabi
  - cd macros && cargo test --no-run && cd -
  - cargo build --examples --release
