language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true

cache: cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

script:
  - rustup target add thumbv6m-none-eabi
  - cd macros && cargo test --no-run && cd -
  - cargo build --examples --release
